name: Build

on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        required: true
        description: 'S3 Bucket name'
      endpoint_url:
        required: true
        description: 'Endpoint URL'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup@main
        with:
          dependencies_type: development

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Restore cached build
        id: restore-build-cache
        uses: actions/cache/restore@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ github.sha }}
      - name: Build
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Cache build output
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Testing
        uses: Beuterei/reusable-workflows/.github/actions/node-qa-testing@main

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ github.sha }}
      - name: Deploy
        uses: Beuterei/reusable-workflows/.github/actions/upload-to-s3@main
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket_name: ${{ inputs.s3_bucket }}
          endpoint: ${{ inputs.endpoint_url }}
          source_path: dist/
