name: Deploy Static App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: Beuterei/reusable-workflows/.github/workflows/deploy-static-app.yml@main
    with:
      project_name: testingsadsdasd
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}