name: Deploy Static App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: Beuterei/reusable-workflows/.github/workflows/deploy-static-app.yml@main
    with:
      project_name: testingsadsdasd
    secrets: inherit