name: Build

on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        required: true
        description: 'S3 Bucket name'
      endpoint_url:
        required: true
        description: 'Endpoint URL'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup@main
        with:
          dependencies_type: development

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Restore cached build
        id: restore-build-cache
        uses: actions/cache@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Build
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Cache build
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ runner.os }}-

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Testing
        uses: Beuterei/reusable-workflows/.github/actions/node-qa-testing@main

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Deploy
        uses: Beuterei/reusable-workflows/.github/actions/upload-to-s3@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ inputs.s3_bucket }}
          endpoint_url: ${{ inputs.endpoint_url }}
          path_to_upload: dist
