name: Build and Deploy a static app

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup@main
        with:
          dependencies_type: development

  linting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name:
        uses: Beuterei/reusable-workflows/.github/actions/eslint-runner@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

