name: QA

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup@main
        with:
          dependencies_type: development

  linting:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      # Default permissions (matching what would be set if the permissions section was missing at all)
      contents: read
      packages: read

      # Need to add these 2 for eslint-annotate-action
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name:
        uses: Beuterei/reusable-workflows/.github/actions/eslint-runner@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

